# Generated by Django 3.2.18 on 2023-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_de_origem', models.CharField(max_length=250)),
                ('nome_fantasia', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('data_de_lancamento', models.DateField()),
            ],
        ),
    ]
